### ISSUE TITLE
Opening FITS-files from memory

### ISSUE THREAD

**Issue by art-den** [simonrw/rust-fitsio#194]
My program receives FITS file from [INDI server](https://indilib.org/develop/developer-manual/92-indi-server.html). I need functionality to open FITS files directly from memory without writing to disk. Is this possible for cfitsio and rust-fitsio?

**Comment by simonrw** [comment]
Hi @art-den , that's a nice suggestion. [`cfitsio` _does_ support opening files from memory with `fits_open_memfile`](https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/c_user/node65.html) however that's not implemented in `cfitsio`. 

What specifically don't you like about saving the file to disk first? A [`NamdTempFile`](https://docs.rs/tempfile/latest/tempfile/struct.NamedTempFile.html) could be used if you don't want the hassle of cleaning up after yourself?

## Approaches

One option is to drop down to using `cfitiso-sys` which is a direct wrapping in Rust of `cfitsio`. This would give you the ability to call whatever `cfitsio` functions you like, except that 

1. they're all unsafe (both in the sense that they require an `unsafe` block to call, and they are wrapped C code so they use raw pointers all over the place)
2. we don't (yet) provide a way to "upgrade" a raw `fitsfile` pointer (as used in `fitsio-sys` and `cfitsio`) into a `fitsio::FitsFile` for use further on.

## Action plan

We could do at least one of two things here:

1. implement `fits_open_memfile` in `fitsio` and allow this method of file reading to be used, and
2. implement a method of upgrading a `fitsio-sys::fitsfile` pointer to a `fitsio::FitsFile`. This would most certainly be `unsafe`, but it would be the last `unsafe` call you'd likely need to make.

I'm not against either option really. I like the symmetry of implementing option 2, since we already implement the inverse in `fitsio::FitsFile::as_raw`. I also think that being able to open a block of memory as a `fitsfile` is a nice idea, except the C api looks nightmareish to support all of the use cases. A custom `mem_realloc` function must be specified if the file needs to grow beyond the memory limits specified, and I don't fancy tackling that any time soon.

@art-den - would you be happy if we just target option 2 for now and allow "upgrading" a `fitsfile` pointer to a `FitsFile`. If your use case is only reading the files, then `NULL` could be passed as the `mem_realloc` function, though this is at your own risk. If we go down this route, I'll make sure to include an example on how to do this for you. Would that be enough?

**Comment by art-den** [comment]
Wow. I just asked about the possibility, but I already see a large number of plans for improvement and pull request also ))

First, why I don't want to save FITS file to disk. I can get one file every 3 seconds. One file is about 50 MB of size. Every minute I will be forced to save 1 GB of data to disk, and every hour - 60 GB. It is not good for SSD (or SD card of Raspberry Pi)
Secondly, for now, any solution even with `unsafe` inside will suit me, to check how my program works. The only functionality I need is to read the parameters and image from the FITS file from memory

**Comment by simonrw** [comment]
Thanks for the nice comment!

I completely understand your use case, I just wanted to make sure we're on the same page!

I've created a PR (#195) with this example: https://github.com/simonrw/rust-fitsio/blob/fix/194/upgrade-from-fitsfile-pointer/fitsio/examples/reading_from_memory.rs#L27-L50

It shows using `fitsoi_sys::ffomem` to open the in-memory pointer (code before that point opens a file and reads it into memory to set up the example. This part will be different for your use case - you will already have `ptr` and `ptr_size`). It then uses `FitsFile::from_raw` to create a `FitsFile` object for further use.

Feel free to install `fitsio` from this branch - in your `Cargo.toml` put:

```toml
fitsio = { git = "https://github.com/simonrw/rust-fitsio", branch = "fix/194/upgrade-from-fitsfile-pointer" }
``` 

and give this branch a go!

**Comment by art-den** [comment]
i'll try to test it a bit later

**Comment by art-den** [comment]
@simonrw , I need some help to build your example. I created new crate and put this contest into `Cargo.toml`:
```toml
[package]
name = "fits_from_mem"
version = "0.1.0"
edition = "2021"

[dependencies]
fitsio = { git = "https://github.com/simonrw/rust-fitsio", branch = "fix/194/upgrade-from-fitsfile-pointer", features = ["default"]}
fitsio-sys = "*"
libc = "*"
```
Then I copypasted your example into `main.rs` except of `use` block. Mine is:
```rust
use fitsio::{FileOpenMode, FitsFile};
use fitsio_sys as sys; // Is this correct btw?
use std::io::Read;
```
Then I tried to build from latest ubuntu and got many errors like
```
error[E0425]: cannot find value `READONLY` in crate `sys`
error[E0425]: cannot find value `stderr` in crate `sys`
```
... and so on

What's my mistake?

**Comment by simonrw** [comment]
@art-den thanks for taking a look. I realise now that there has been a mistake in the way I've laid out `fitsio` and `fitsio-sys`. 

Your issue is caused by the version of `fitsio-sys` on `crates.io` being outdated, but this led me to realise a more critical error on my part.

Rust only allows one crate to exist in the list of packages that links against a system library. I was getting compile errors when trying to re-create your problem to do with multiple crates linking to `cfitsio`. This is because I was getting different versions of `fitsio-sys` included in my crate chain.

I've made a change to `fitsio` to re-export `fitsio-sys` as `sys` so only `fitsio` should be included, and you get `fitsio-sys` for free for these sorts of situations.

If you update your `use` statements to read:

```rust
use fitsio::{sys, FileOpenMode, FitsFile};
use std::io::Read;
```

does that work?

Thank you so much for making me realise this, the changes I've made should make the two crates operate much nicer together :tada:

**Comment by art-den** [comment]
with
```rust
use fitsio::{sys, FileOpenMode, FitsFile};
use std::io::Read;
```
I got error 
```
error[E0603]: crate `sys` is private
```
But this is not a problem for me now as I did temporary FITS file writing (as you suggested) for development and debugging.

**Comment by simonrw** [comment]
Hi @art-den - it sounds like Cargo did not re-fetch from the branch. Since I have pushed new commits to the branch, you may need to remove your `Cargo.lock` file and try building again - is that ok?

**Comment by art-den** [comment]
I removed `Cargo.lock` and now it builds. Thanks!

**Comment by simonrw** [comment]
Great, is the change I made in #195 enough for your needs do you think?

**Comment by art-den** [comment]
Not so fast)) I'm currently trying to solve other problems related to astrophotography through the INDI server. I'll be sure to post the results with your pull request later.

**Comment by simonrw** [comment]
@art-den I've closed the issue but if you still have problems, please let us know. You can either re-open this issue or create a new one, whichever you prefer. I think the changes made in #195 are worth merging regardless of if they fix your issue.

**Comment by art-den** [comment]
Tried using it again (instead of saving a temp file) and it works. Thank you!

**Comment by art-den** [comment]
Build under msys is broken:
```
error: failed to run custom build command for `fitsio-sys v0.5.0`

Caused by:
  process didn't exit successfully: `D:\rust\live_stacking\target\debug\build\fitsio-sys-58e5685ff357160f\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=CFITSIO >= 3.37_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=CFITSIO >= 3.37_STATIC
  cargo:rerun-if-env-changed=CFITSIO >= 3.37_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'Unhandled error: `"pkg-config" "--libs" "--cflags" "cfitsio >= 3.37"` did not exit successfully: exit code: 1
  error: could not find system library 'cfitsio >= 3.37' required by the 'fitsio-sys' crate

  --- stderr
  Package dependency requirement 'cfitsio >= 3.37' could not be satisfied.
  Package 'cfitsio' has version '.', required version is '>= 3.37'
  ', E:\Development\vscode\tools\rust\cargo\registry\src\github.com-1ecc6299db9ec823\fitsio-sys-0.5.0\build.rs:32:19       
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

 *  The terminal process "E:\Development\vscode\tools\rust\cargo\bin\cargo.exe 'build'" terminated with exit code: 101. 
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: E:\Development\vscode\tools\rust\cargo\bin\cargo.exe build 

    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on build directory
   Compiling libc v0.2.138
   Compiling thiserror v1.0.38      
   Compiling crossbeam-epoch v0.9.13
   Compiling fitsio-sys v0.5.0       
   Compiling crossbeam-channel v0.5.6
   Compiling num_cpus v1.15.0        
   Compiling serde v1.0.151
   Compiling flate2 v1.0.25
   Compiling field-offset v0.3.4
   Compiling itoa v1.0.5
   Compiling ryu v1.0.12
   Compiling anyhow v1.0.68
error: failed to run custom build command for `fitsio-sys v0.5.0`

Caused by:
  process didn't exit successfully: `D:\rust\live_stacking\target\debug\build\fitsio-sys-58e5685ff357160f\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=CFITSIO >= 3.37_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=CFITSIO >= 3.37_STATIC
  cargo:rerun-if-env-changed=CFITSIO >= 3.37_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'Unhandled error: `"pkg-config" "--libs" "--cflags" "cfitsio >= 3.37"` did not exit successfully: exit code: 1
  error: could not find system library 'cfitsio >= 3.37' required by the 'fitsio-sys' crate

  --- stderr
  Package dependency requirement 'cfitsio >= 3.37' could not be satisfied.
  Package 'cfitsio' has version '.', required version is '>= 3.37'
  ', E:\Development\vscode\tools\rust\cargo\registry\src\github.com-1ecc6299db9ec823\fitsio-sys-0.5.0\build.rs:32:19       
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Info about my cfitsio package:
```
$ pacman -Q --info mingw-w64-x86_64-cfitsio
Name            : mingw-w64-x86_64-cfitsio
Version         : 1~3.48-1
Description     : A library of C and Fortran subroutines for reading and writing data files in FITS
                  (Flexible Image Transport System) data format (mingw-w64)
Architecture    : any
URL             : https://heasarc.gsfc.nasa.gov/fitsio/
Licenses        : custom
Groups          : None
Provides        : None
Depends On      : mingw-w64-x86_64-gcc-libs  mingw-w64-x86_64-zlib
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 3.93 MiB
Packager        : CI (msys2-autobuild/16f20bf2/896880892)
Build Date      : Tue Jun 1 22:33:14 2021
Install Date    : Wed Dec 21 01:02:24 2022
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by simonrw** [comment]
Do you mind if we move this to another issue? This is presumably related to how `cfitsio` is found on `msys2` not being compatible.
